# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2048M

# Fabric Properties
minecraft_version=1.21
yarn_mappings=1.21+build.9
loader_version=0.16.9

# Dependencies
fabric_version=0.100.8+1.21
cloth_config_version=15.0.127
modmenu_version=11.0.1

# Mod Properties
mod_version=0.1.0
maven_group=dev.hazard
archives_base_name=potionoptimizer
